/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import javax.swing.JOptionPane;
import config.dataBase;
import java.sql.SQLException;

/**
 *
 * @author Abu Aqila Balawi
 */
public class form_regist extends javax.swing.JFrame {

    /**
     * Creates new form form_regist
     */
    public form_regist() {
        initComponents();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_regist = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        j_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        j_emailaddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(78, 19, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(1041, 646));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(111, 26, 7));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_regist.setBackground(new java.awt.Color(78, 19, 4));
        jb_regist.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jb_regist.setForeground(new java.awt.Color(255, 255, 255));
        jb_regist.setText("LOGIN");
        jb_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registActionPerformed(evt);
            }
        });
        jPanel2.add(jb_regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 100, 40));

        jButton1.setBackground(new java.awt.Color(78, 19, 4));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 40));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 269, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 269, -1));

        j_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(j_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 269, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 269, -1));

        j_emailaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_emailaddressActionPerformed(evt);
            }
        });
        jPanel2.add(j_emailaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 269, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email address");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 269, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGIST NOW !");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 240, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 350, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void j_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_usernameActionPerformed

    private void j_emailaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_emailaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_emailaddressActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jb_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registActionPerformed
        
        // Ini untuk ke menu selanjutnya(Menu login)
        form_login login = new form_login();
        login.setVisible(true);
        login.revalidate();
        
        dispose();
    }//GEN-LAST:event_jb_registActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String username = j_username.getText();
        String password =new String( jPasswordField1.getPassword());
        String emailAddress = j_emailaddress.getText();
        
        // ini untuk memastikan data tidak boleh kosong.
        if (username.isEmpty() || password.isEmpty() || emailAddress.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon Maaf Data Tidak Boleh Kosong!", "Coba Lagi", JOptionPane.ERROR_MESSAGE);
            return;
        }
      
        // ini memasitikan username tidak boleh menggunakan simbol.
         if(!username.matches("[a-zA-Z0-9]+")){
             JOptionPane.showMessageDialog(this,"Username Hanya boleh Huruf dan angka", "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
             return;
         }
         
          // ini untuk memastikan pasword minimal 8 karakter.
         if(password.length()< 8){
            JOptionPane.showMessageDialog(this, "Pasword minimal 8 karakter","Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
            return;
         }
         
         // ini koneksi database nya.
          try {
                dataBase db = new dataBase(); // Panggil koneksi
                db.koneksi(); // Koneksikan ke DB

                String query = "INSERT INTO dataluckypawpetshop (username, password, Emailaddress) VALUES (?, ?, ?)";
                db.pst = db.con.prepareStatement(query);
                db.pst.setString(1, username);
                db.pst.setString(2, password);
                db.pst.setString(3, emailAddress);

                int result = db.pst.executeUpdate();
                if (result > 0) {
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil!");
        // Kosongkan field setelah berhasil
                j_username.setText("");
                jPasswordField1.setText("");
                j_emailaddress.setText("");
         } else {
                JOptionPane.showMessageDialog(this, "Registrasi Gagal. Coba Lagi!");
        }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_regist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField j_emailaddress;
    private javax.swing.JTextField j_username;
    private javax.swing.JButton jb_regist;
    // End of variables declaration//GEN-END:variables
}
