/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;
import config.dataBase;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author Abu Aqila Balawi
 */
public class grooming extends javax.swing.JPanel {

    /**
     * Creates new form grooming
     */
    public grooming() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_utama = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_alamatBooking = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jdc_tanggalBooking = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jt_namaBooking = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jb_booking = new javax.swing.JButton();

        pn_utama.setBackground(new java.awt.Color(102, 0, 0));
        pn_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 26, 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jta_alamatBooking.setColumns(20);
        jta_alamatBooking.setRows(5);
        jScrollPane1.setViewportView(jta_alamatBooking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 185, 248, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 164, 248, -1));
        jPanel1.add(jdc_tanggalBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 136, 248, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 115, 248, -1));

        jt_namaBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_namaBookingActionPerformed(evt);
            }
        });
        jPanel1.add(jt_namaBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 87, 248, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 66, 248, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BOOKING");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 6, 178, 54));

        jb_booking.setBackground(new java.awt.Color(78, 19, 4));
        jb_booking.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jb_booking.setForeground(new java.awt.Color(255, 255, 255));
        jb_booking.setText("BOOKING");
        jb_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_bookingActionPerformed(evt);
            }
        });
        jPanel1.add(jb_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 283, 103, 33));

        pn_utama.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 290, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_namaBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_namaBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_namaBookingActionPerformed

    private void jb_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_bookingActionPerformed
        // TODO add your handling code here:
            String nama = jt_namaBooking.getText();
            Date tanggal = jdc_tanggalBooking.getDate();
            String alamat = jta_alamatBooking.getText();

            // ini untuk memastikan data tidak boleh kosong.
            if (nama.isEmpty() || alamat.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Mohon Maaf Data Tidak Boleh Kosong!", "Coba Lagi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (tanggal == null){
                JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong");
                return;
            } 
            java.sql.Date tanggalSQL = new java.sql.Date(tanggal.getTime());

             // ini koneksi database nya.
              try {
                    dataBase db = new dataBase(); // Panggil koneksi
                    db.koneksi(); // Koneksikan ke DB

                    String query = "INSERT INTO datagroming (nama, tanggal, alamat) VALUES (?, ?, ?)";
                    db.pst = db.con.prepareStatement(query);
                    db.pst.setString(1, nama);
                    db.pst.setDate(2, tanggalSQL);
                    db.pst.setString(3, alamat);

                    int result = db.pst.executeUpdate();
                    if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Booking Berhasil!");
            // Kosongkan field setelah berhasil
                    jt_namaBooking.setText("");
                    jdc_tanggalBooking.setDate(null);
                    jta_alamatBooking.setText("");
             } else {
                    JOptionPane.showMessageDialog(this, "Booking Gagal. Coba Lagi!");
            }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        
    }//GEN-LAST:event_jb_bookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_booking;
    private com.toedter.calendar.JDateChooser jdc_tanggalBooking;
    private javax.swing.JTextField jt_namaBooking;
    private javax.swing.JTextArea jta_alamatBooking;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
