/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

/**
 *
 * @author irfan tarjianto
 */
public class statusbooking extends javax.swing.JPanel {

    /**
     * Creates new form statusbooking
     */
    public statusbooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_statusbooking = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_statusbooking.setBackground(new java.awt.Color(78, 19, 4));

        javax.swing.GroupLayout pn_statusbookingLayout = new javax.swing.GroupLayout(pn_statusbooking);
        pn_statusbooking.setLayout(pn_statusbookingLayout);
        pn_statusbookingLayout.setHorizontalGroup(
            pn_statusbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pn_statusbookingLayout.setVerticalGroup(
            pn_statusbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        add(pn_statusbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 750, 410));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STATUS BOOKING");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pn_statusbooking;
    // End of variables declaration//GEN-END:variables
}
